version: 2
jobs:
  build:
    machine:
       docker_layer_caching: true
    steps:
    - checkout
    - run:
        name: Compile TypeScript
        command: make build
    - run:
        name: Run tests
        command: make test-local